#!/bin/bash
## A calculator in pure-bash.
## I even made a pure-bash lexer for this.
## Not gonna lie I feel pretty accomplished right now.
## ---------------------------------------------------
## Created by: Phate6660 [https://github.com/Phate6660]
## Dependencies: Only bash ;)

# Get the first arg (since that's all we need), and add a space betweem each character.
args="$1"
for ((i=0; i<${#args}; i++)); do
    args_spaces+="${args:${i}:1} "
done

# Read each space-separated character into the array.
# shellcheck disable=SC2162
read -a args_array <<< "${args_spaces}"

# Iterate over the argument array.
n=0
for char in "${args_array[@]}"; do
    # Check if "$char" is a parenthesis, and if so append to final_array.
    if [ "${char}" == "(" ] || [ "${char}" == ")" ]; then
        final_array+=("${char}")
        continue
    # Check if "$char" is a square bracket, and if so append to final_array.
    elif [ "${char}" == "[" ] || [ "${char}" == "]" ]; then
        final_array+=("${char}")
        continue
    # Check if "$char" is a number, and if so append to final_array.
    elif [[ "${char}" =~ ^[0-9]+$ ]]; then
        final_array+=("${char}")
        continue
    # Check if "$char" is a math operation, and if so append to final_array.
    elif [ "${char}" == "*" ] || [ "${char}" == "/" ] || [ "${char}" == "+" ] || [ "${char}" == "-" ]; then
        # Up n by 1 before and after appending the math operation to account for array index offsets.
        n=$((n + 1))
        final_array+=("${char}")
        n=$((n + 1))
        continue
    else
        # If the character isn't a square bracket, digit, or math operation, display an error message and exit.
        echo -e "Only digits, parenthesis, square brackets, '*', '/', '+', and '-', are supported.\n'${i}' is currently unsupported." && exit 1
    fi
done

if [ "$2" == "--debug" ]; then
    echo "final_array = ${final_array[*]}"
fi

final_array_count="${#final_array[@]}"
a=0
for ((b=0;b<=final_array_count;b++)); do
    if [ "${b}" = "${final_array_count}" ]; then
        # No more looping is needed, break.
        break
    else
        # The next 2 if statements are for dealing with brackets, which are used to signify multi-digit numbers.
        if [ "${final_array[${b}]}" == "(" ]; then
            paren=true
            continue
        elif [ "${final_array[${b}]}" == ")" ]; then
            paren=false
            ip="${ip[*]}"
            ip="${ip// /}"
            ip=$(("${ip}"))
            if [ "$2" == "--debug" ]; then
                echo "ip = ${ip}"
            fi
            number_array+=("$ip")
            unset ip
            continue
        elif [ "${final_array[${b}]}" == "[" ]; then
            multi=true
            continue
        elif [ "${final_array[${b}]}" == "]" ]; then
            multi=false
            mn="${mn[*]}"
            mn="${mn// /}"
            if [ "$2" == "--debug" ]; then
                echo "mn = ${mn}"
            fi
            number_array+=("${mn}")
            unset mn
            continue
        # If the element is a number...
        elif [[ "${final_array[${b}]}" =~ ^[0-9]+$ ]]; then
            # If "$multi" hasn't been set, append to number_array like normal.
            if [ -n "${multi}" ] || [ -n "${paren}" ]; then
                # If "$multi is true", append the contents of the element to the mn variable.
                if [ "${paren}" == true ]; then
                    ip+=("${final_array[${b}]}")
                    continue
                elif [ "${multi}" == true ]; then
                        mn+=("${final_array[${b}]}")
                        continue
                else
                    number_array+=("${final_array[${b}]}")
                    continue
                fi
            else
                number_array+=("${final_array[${b}]}")
                continue
            fi
        # If the element is an operation, append to operation_array.
        elif [ "${final_array[${b}]}" == "*" ] || [ "${final_array[${b}]}" == "/" ] || [ "${final_array[${b}]}" == "+" ] || [ "${final_array[${b}]}" == "-" ]; then
            if [ -n "${paren}" ]; then
                if [ "${paren}" == true ]; then
                    ip+=("${final_array[${b}]}")
                     continue
                else
                    operation_array+=("${final_array[${b}]}")
                    continue
                fi
            else
                operation_array+=("${final_array[${b}]}")
                a=$((a + 1))
                continue
            fi
        fi
    fi
done

number_count="${#number_array[@]}"
operation_count="${#operation_array[@]}"

if [ -n "${paren}" ] || [ -n "${multi}" ]; then
    number_array=("${number_array[@]:2}")
    number_count=$((number_count - 2))
fi

if [ "$2" == "--debug" ]; then
    for ((e=0;e<=number_count;e++)); do
        echo "number_array[$e] = ${number_array[$e]}"
        for ((f=0;f<=operation_count;f++)); do
            echo "operation_array[$f] = ${operation_array[$f]}"
        done
    done
    echo -e "number_count = ${number_count}\noperation_count = ${operation_count}"
fi

c=0
for ((d=0;d<=final_array_count;d++)); do
    if [ "${d}" = "${number_count}" ]; then
        break
    else
        calculation_array+=("${number_array[${c}]}")
        if [ "${d}" == "${operation_count}" ]; then
            continue
        else
            calculation_array+=("${operation_array[${c}]}")
            c=$((c + 1))
            continue
        fi
    fi
done

calculation="${calculation_array[*]}"
calculation="${calculation// /}"
if [ "$2" == "--debug" ]; then
    echo "calculation = ${calculation}"
fi
echo $(("${calculation}"))
