#!/bin/bash
## Tests for bcalc

## Common variables used for the tests.
exe="./bcalc"

## Basic math operations.
# Parenthesis
basic_paren() {
    # Local to keep them in the function.
    local expected="8"
    local command="$exe '(2+2)*2'"
    local result="$(eval "${command}")"
    
    if [ "${result}" == "${expected}" ]; then
        basic_paren_test="GOOD -- The parenthesis test has passed."
    else
        basic_paren_test="BAD -- The result of the parenthesis test is \"${result}\", when it should be \"${expected}\"."
    fi
}

basic_paren && echo "${basic_paren_test}" || echo "Failed to run the basic parenthesis test!" && exit 1
